DROP DATABASE QUANLYTAISAN_VERSION2

CREATE DATABASE QUANLYTAISAN_VERSION2

GO
USE QUANLYTAISAN_VERSION2
GO

CREATE TABLE VAITRO(
	 ID INT PRIMARY KEY ,
	 TENVAITRO NVARCHAR(20) NOT NULL
)

CREATE TABLE TAIKHOAN (
	ID INT IDENTITY PRIMARY KEY ,
	TENTAIKHOAN VARCHAR(30) NOT NULL ,
	MATKHAU VARCHAR(20) NOT NULL ,
	NHANVIEN VARCHAR(7) NOT NULL ,
	TINHTRANG BIT NOT NULL DEFAULT (0),
	VAITRO INT NOT NULL FOREIGN KEY REFERENCES VAITRO(ID)
)

CREATE TABLE PHONGBAN(
 ID VARCHAR(7) PRIMARY KEY ,
 TENPHONGBAN NVARCHAR(50) UNIQUE NOT NULL
)

CREATE TABLE NHANVIEN (
	ID VARCHAR(7)  PRIMARY KEY ,
	TENNHANVIEN NVARCHAR(50) NOT NULL ,
	GIOITINH BIT DEFAULT (1) NOT NULL ,
	NGAYSINH DATE NOT NULL ,
	EMAIL VARCHAR(50) UNIQUE NOT NULL ,
	PHONGBAN VARCHAR(7) NOT NULL FOREIGN KEY REFERENCES PHONGBAN(ID)
)

CREATE TABLE QUOCGIA (
 ID VARCHAR(5) PRIMARY KEY ,
 TENQUOCGIA NVARCHAR(20) UNIQUE NOT NULL
)

CREATE TABLE NHASANXUAT (
	ID INT IDENTITY PRIMARY KEY ,
	TENNHASANXUAT NVARCHAR(50) NOT NULL ,
	QUOCGIA VARCHAR(5) NOT NULL FOREIGN KEY REFERENCES QUOCGIA(ID)
)

CREATE TABLE PHANLOAI (
	ID INT IDENTITY PRIMARY KEY ,
	TENPHANLOAI NVARCHAR(30) NOT NULL UNIQUE
)

CREATE TABLE KHO (
	 ID INT IDENTITY PRIMARY KEY ,
	 TENKHO NVARCHAR(30) NOT NULL UNIQUE
)

CREATE TABLE TAISAN (
		ID VARCHAR(7) NOT NULL PRIMARY KEY ,
		TENTAISAN NVARCHAR(30) NOT NULL ,
		MOTA NTEXT ,
		NGUYENGIA INT NOT NULL ,
		THOIGIANKHAUHAO INT NOT NULL ,
		TYLEKHAUHAO FLOAT NOT NULL ,
		NAMBDSUDUNG INT,
		TINHTRANG BIT DEFAULT (0), -- 0: trong kho , 1: đang sử dụng
		NHASANXUAT INT NOT NULL FOREIGN KEY REFERENCES NHASANXUAT(ID),
		PHANLOAI INT NOT NULL FOREIGN KEY REFERENCES PHANLOAI(ID),
		KHO INT NOT NULL FOREIGN KEY REFERENCES KHO(ID)
)

CREATE TABLE PHIEUBANGIAO (
		ID VARCHAR(7) NOT NULL PRIMARY KEY ,
		NGAYLAP DATE NOT NULL DEFAULT (GETDATE()),
		NHANVIENBANGIAO VARCHAR(7) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(ID),
		NHANVIENNHAN VARCHAR(7) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(ID),
		KHO INT NOT NULL FOREIGN KEY REFERENCES KHO(ID)
)

CREATE TABLE PHIEUBANGIAOCHITIET (
	 ID INT IDENTITY PRIMARY KEY ,
	 NGUOISUDUNG VARCHAR (50) NULL,
	 TAISAN VARCHAR(7) NOT NULL FOREIGN KEY REFERENCES TAISAN(ID),
	 PHIEUBANGIAO VARCHAR(7) NOT NULL FOREIGN KEY REFERENCES PHIEUBANGIAO(ID)
)

CREATE TABLE PHIEUTHUHOI (
  ID VARCHAR (7) NOT NULL PRIMARY KEY,
  NGAYLAP DATE NOT NULL DEFAULT (GETDATE()),
  NHANVIENNHAN VARCHAR (7) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(ID),
  NHANVIENTRA VARCHAR (7) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(ID),
  KHO INT NOT NULL FOREIGN KEY REFERENCES KHO(ID)
)

CREATE TABLE PHIEUTHUHOICHITIET (
  ID INT IDENTITY PRIMARY KEY ,
  TAISAN VARCHAR (7) NOT NULL FOREIGN KEY REFERENCES TAISAN(ID),
  PHIEUTHUHOI VARCHAR (7) NOT NULL FOREIGN KEY REFERENCES PHIEUTHUHOI(ID)
)

